import {
  OrbitControls,
} from "@react-three/drei";
import Head from "next/head";
import { Canvas } from "@react-three/fiber";
import { Scene1 } from "~/Scene1";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-screen flex-col">
        <Canvas 
        style={{ background: "#000000" }}
        >
          {/* <ambientLight intensity={Math.PI / 2} /> */}
        
          <Scene1 />
          <OrbitControls />
        </Canvas>
      </div>
    </>
  );
}
